name: yoga-classes-backend

on:
  push:
    branches: [DockerImage]
    paths:
      - "yoga-classes-backend/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Create .env file
        run: |
          echo "PORT=${{ secrets.PORT }}" >> .env
          echo "DB_USERNAME=${{ secrets.DB_USERNAME }}" >> .env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
          echo "DB_NAME=${{ secrets.DB_NAME }}" >> .env
          echo "DB_HOST=${{ secrets.DB_HOST }}" >> .env
          echo "DB_PORT=${{ secrets.DB_PORT }}" >> .env
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env
          echo "BUCKET_NAME=${{ secrets.BUCKET_NAME }}" >> .env
          echo "BUCKET_REGION=${{ secrets.BUCKET_REGION }}" >> .env
          echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> .env
          echo "AWS_SECRET=${{ secrets.AWS_SECRET }}" >> .env
          
      - name: Build docker image
        run: docker build -t adarshmanwal9/yoga-backend ./yoga-classes-backend
      - name: Publish image to docker hub
        run: docker push adarshmanwal9/yoga-backend:latest

  deploy:
    needs: build
    runs-on: [aws-ec2]
    steps:
      - name: Pull image from docker hub
        run: docker pull adarshmanwal9/yoga-backend
      - name: Delete old container
        run: docker rm -f yoga-backend-container
      - name: Run docker container
        run: docker run -d -p 3000:3000 --env-file .env --name yoga-backend-container adarshmanwal9/yoga-backend:latest

