name: Yoga Classes Backend CI/CD

on:
  push:
    branches: [main]
    paths:
      - "yoga-classes-backend/**"
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Create .env file
        run: |
          echo "PORT=${{ secrets.PORT }}" >> .env
          echo "DB_USERNAME=${{ secrets.DB_USERNAME }}" >> .env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
          echo "DB_NAME=${{ secrets.DB_NAME }}" >> .env
          echo "DB_HOST=${{ secrets.DB_HOST }}" >> .env
          echo "DB_PORT=${{ secrets.DB_PORT }}" >> .env
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env
          echo "BUCKET_NAME=${{ secrets.BUCKET_NAME }}" >> .env
          echo "BUCKET_REGION=${{ secrets.BUCKET_REGION }}" >> .env
          echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> .env
          echo "AWS_SECRET=${{ secrets.AWS_SECRET }}" >> .env
          
      - name: Build docker image
        run: docker build -t adarshmanwal9/yoga-backend ./yoga-classes-backend
      - name: Publish image to docker hub
        run: docker push adarshmanwal9/yoga-backend:latest

  deploy:
    needs: build
    runs-on: [aws-ec2]
    steps:
      - name: Pull image from docker hub
        run: docker pull adarshmanwal9/yoga-backend
      - name: Delete old container
        run: docker rm -f yoga-backend-container
      - name: Run docker container
        run: |
          docker run -d -p 3000:3000 \
            -e PORT=${{ secrets.PORT }} \
            -e DB_USERNAME=${{ secrets.DB_USERNAME }} \
            -e DB_PASSWORD=${{ secrets.DB_PASSWORD }} \
            -e DB_NAME=${{ secrets.DB_NAME }} \
            -e DB_HOST=${{ secrets.DB_HOST }} \
            -e DB_PORT=${{ secrets.DB_PORT }} \
            -e JWT_SECRET=${{ secrets.JWT_SECRET }} \
            -e BUCKET_NAME=${{ secrets.BUCKET_NAME }} \
            -e BUCKET_REGION=${{ secrets.BUCKET_REGION }} \
            -e AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} \
            -e AWS_SECRET=${{ secrets.AWS_SECRET }} \
            --name yoga-backend-container \
            adarshmanwal9/yoga-backend:latest

